name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  push:
    name: Metasploit image build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.51

      - name: Build Docker image
        run: docker build --no-cache --rm --file=Dockerfile.metasploit --tag=diodonfrost/metasploit:latest .

      - name: Test Docker image
        run: |
          container_id=$(mktemp)
          sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro diodonfrost/metasploit:latest sleep 300 > "${container_id}"

          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
